### ISSUE TITLE
Not included in core

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-kramer-vs41h#1]
@SteveTherrien This module is not in either the backport 1.4 branch or the master 2.0 branch. How is it coming along? Did anyone test it?

**Comment by SteveTherrien** [comment]
This module is untested and I don't have a way to test it.

It was made because of [this request](https://github.com/bitfocus/companion-module-requests/issues/74), but the original requester never got back to us.

We should probably archive this repo to avoid any future confusion.

**Comment by josephdadams** [comment]
This is in core now. Anyone with issue can file a bug report.
